name: Notebook Check Pull Request

on:
  pull_request_target:
    types: [opened, reopened]

# Restrict permissions by default
permissions: {}

jobs:
  comment-welcome:
    permissions:
      contents: read
      pull-requests: write  # Required for commenting on PRs
    
    runs-on: ubuntu-latest
    timeout-minutes: 10
    
    steps:
    - name: Fetch pull request branch
      uses: actions/checkout@8ade135a41bc03ea155e62e844d188df1ea18608 # v4.1.0
      with:
        repository: ${{ github.event.pull_request.head.repo.full_name }}
        ref: ${{ github.event.pull_request.head.sha }}
        
    - name: Fetch base develop branch
      run: git fetch -u "$GITHUB_SERVER_URL/$GITHUB_REPOSITORY" develop:develop
      
    - name: Create message
      env:
        HEAD_REPOSITORY: ${{ github.event.pull_request.head.repo.full_name }}
        HEAD_REF: ${{ github.event.pull_request.head.ref }}
        PR_NUM: ${{ github.event.pull_request.number }}
      run: |
        # Preview links and tool usage only needed for notebook changes.
        readarray -t changed_notebooks < <(git diff --name-only develop | grep '\.ipynb$' || true)
        if [[ ${#changed_notebooks[@]} == 0 ]]; then
          echo "No notebooks modified in this pull request."
        else
          msg="<h4>Preview</h4>\n"
          msg+="Preview and run these notebook edits with Google Colab:\n<ul>\n"
          # Link to PR branch in user's fork that is always current.
          for fp in "${changed_notebooks[@]}"; do
            gh_path="${HEAD_REPOSITORY}/blob/${HEAD_REF}/${fp}"
            colab_url="https://colab.research.google.com/github/${gh_path}"
            msg+="<li><a href='${colab_url}'>${fp}</a></li>\n"
          done
          msg+="</ul>\n"

          reviewnb_url="https://app.reviewnb.com/${GITHUB_REPOSITORY}/pull/${PR_NUM}/files/"
          msg+="Rendered <a href='${reviewnb_url}'>notebook diffs</a> available on ReviewNB.com.\n"

          msg+="If commits are added to the pull request, synchronize your local branch: <code>git pull origin $HEAD_REF</code>\n"
        fi
        echo "MESSAGE=$msg" >> $GITHUB_ENV

    - name: Find Comment
      uses: peter-evans/find-comment@a54c31d7fa095754bfef525c0c8e5e5674c4b4b1 # v2.4.0
      id: find-comment
      with:
        issue-number: ${{ github.event.pull_request.number }}
        body-includes: Preview and run these notebook edits
        comment-author: github-actions[bot]

    - name: Add or update comment
      uses: peter-evans/create-or-update-comment@23ff15729ef2fc348714a3bb66d2f655ca9066f2 # v3.1.0
      if: env.MESSAGE != ''
      with:
        comment-id: ${{ steps.find-comment.outputs.comment-id }}
        issue-number: ${{ github.event.pull_request.number }}
        body: ${{ env.MESSAGE }}
        edit-mode: replace
